//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.09 at 01:50:25 PM CET 
//


package at.spot.prestashop.rest;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the at.spot.prestashop.rest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: at.spot.prestashop.rest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PrestashopProduct }
     * 
     */
    public PrestashopProduct createPrestashop() {
        return new PrestashopProduct();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product }
     * 
     */
    public PrestashopProduct.Product createPrestashopProduct() {
        return new PrestashopProduct.Product();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.Associations }
     * 
     */
    public PrestashopProduct.Product.Associations createPrestashopProductAssociations() {
        return new PrestashopProduct.Product.Associations();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.Associations.ProductBundle }
     * 
     */
    public PrestashopProduct.Product.Associations.ProductBundle createPrestashopProductAssociationsProductBundle() {
        return new PrestashopProduct.Product.Associations.ProductBundle();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.Associations.Accessories }
     * 
     */
    public PrestashopProduct.Product.Associations.Accessories createPrestashopProductAssociationsAccessories() {
        return new PrestashopProduct.Product.Associations.Accessories();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.Associations.StockAvailables }
     * 
     */
    public PrestashopProduct.Product.Associations.StockAvailables createPrestashopProductAssociationsStockAvailables() {
        return new PrestashopProduct.Product.Associations.StockAvailables();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.Associations.Tags }
     * 
     */
    public PrestashopProduct.Product.Associations.Tags createPrestashopProductAssociationsTags() {
        return new PrestashopProduct.Product.Associations.Tags();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.Associations.ProductFeatures }
     * 
     */
    public PrestashopProduct.Product.Associations.ProductFeatures createPrestashopProductAssociationsProductFeatures() {
        return new PrestashopProduct.Product.Associations.ProductFeatures();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.Associations.ProductOptionValues }
     * 
     */
    public PrestashopProduct.Product.Associations.ProductOptionValues createPrestashopProductAssociationsProductOptionValues() {
        return new PrestashopProduct.Product.Associations.ProductOptionValues();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.Associations.Images }
     * 
     */
    public PrestashopProduct.Product.Associations.Images createPrestashopProductAssociationsImages() {
        return new PrestashopProduct.Product.Associations.Images();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.Associations.Categories }
     * 
     */
    public PrestashopProduct.Product.Associations.Categories createPrestashopProductAssociationsCategories() {
        return new PrestashopProduct.Product.Associations.Categories();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.AvailableLater }
     * 
     */
    public PrestashopProduct.Product.AvailableLater createPrestashopProductAvailableLater() {
        return new PrestashopProduct.Product.AvailableLater();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.AvailableNow }
     * 
     */
    public PrestashopProduct.Product.AvailableNow createPrestashopProductAvailableNow() {
        return new PrestashopProduct.Product.AvailableNow();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.DescriptionShort }
     * 
     */
    public PrestashopProduct.Product.DescriptionShort createPrestashopProductDescriptionShort() {
        return new PrestashopProduct.Product.DescriptionShort();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.Description }
     * 
     */
    public PrestashopProduct.Product.Description createPrestashopProductDescription() {
        return new PrestashopProduct.Product.Description();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.Name }
     * 
     */
    public PrestashopProduct.Product.Name createPrestashopProductName() {
        return new PrestashopProduct.Product.Name();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.LinkRewrite }
     * 
     */
    public PrestashopProduct.Product.LinkRewrite createPrestashopProductLinkRewrite() {
        return new PrestashopProduct.Product.LinkRewrite();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.MetaTitle }
     * 
     */
    public PrestashopProduct.Product.MetaTitle createPrestashopProductMetaTitle() {
        return new PrestashopProduct.Product.MetaTitle();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.MetaKeywords }
     * 
     */
    public PrestashopProduct.Product.MetaKeywords createPrestashopProductMetaKeywords() {
        return new PrestashopProduct.Product.MetaKeywords();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.MetaDescription }
     * 
     */
    public PrestashopProduct.Product.MetaDescription createPrestashopProductMetaDescription() {
        return new PrestashopProduct.Product.MetaDescription();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.Associations.ProductBundle.Products }
     * 
     */
    public PrestashopProduct.Product.Associations.ProductBundle.Products createPrestashopProductAssociationsProductBundleProducts() {
        return new PrestashopProduct.Product.Associations.ProductBundle.Products();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.Associations.StockAvailables.StockAvailable }
     * 
     */
    public PrestashopProduct.Product.Associations.StockAvailables.StockAvailable createPrestashopProductAssociationsStockAvailablesStockAvailable() {
        return new PrestashopProduct.Product.Associations.StockAvailables.StockAvailable();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.Associations.Tags.Tag }
     * 
     */
    public PrestashopProduct.Product.Associations.Tags.Tag createPrestashopProductAssociationsTagsTag() {
        return new PrestashopProduct.Product.Associations.Tags.Tag();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.Associations.ProductFeatures.ProductFeature }
     * 
     */
    public PrestashopProduct.Product.Associations.ProductFeatures.ProductFeature createPrestashopProductAssociationsProductFeaturesProductFeature() {
        return new PrestashopProduct.Product.Associations.ProductFeatures.ProductFeature();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.Associations.ProductOptionValues.ProductOptionsValues }
     * 
     */
    public PrestashopProduct.Product.Associations.ProductOptionValues.ProductOptionsValues createPrestashopProductAssociationsProductOptionValuesProductOptionsValues() {
        return new PrestashopProduct.Product.Associations.ProductOptionValues.ProductOptionsValues();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.Associations.Images.Image }
     * 
     */
    public PrestashopProduct.Product.Associations.Images.Image createPrestashopProductAssociationsImagesImage() {
        return new PrestashopProduct.Product.Associations.Images.Image();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.Associations.Categories.Category }
     * 
     */
    public PrestashopProduct.Product.Associations.Categories.Category createPrestashopProductAssociationsCategoriesCategory() {
        return new PrestashopProduct.Product.Associations.Categories.Category();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.AvailableLater.Language }
     * 
     */
    public PrestashopProduct.Product.AvailableLater.Language createPrestashopProductAvailableLaterLanguage() {
        return new PrestashopProduct.Product.AvailableLater.Language();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.AvailableNow.Language }
     * 
     */
    public PrestashopProduct.Product.AvailableNow.Language createPrestashopProductAvailableNowLanguage() {
        return new PrestashopProduct.Product.AvailableNow.Language();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.DescriptionShort.Language }
     * 
     */
    public PrestashopProduct.Product.DescriptionShort.Language createPrestashopProductDescriptionShortLanguage() {
        return new PrestashopProduct.Product.DescriptionShort.Language();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.Description.Language }
     * 
     */
    public PrestashopProduct.Product.Description.Language createPrestashopProductDescriptionLanguage() {
        return new PrestashopProduct.Product.Description.Language();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.Name.Language }
     * 
     */
    public PrestashopProduct.Product.Name.Language createPrestashopProductNameLanguage() {
        return new PrestashopProduct.Product.Name.Language();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.LinkRewrite.Language }
     * 
     */
    public PrestashopProduct.Product.LinkRewrite.Language createPrestashopProductLinkRewriteLanguage() {
        return new PrestashopProduct.Product.LinkRewrite.Language();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.MetaTitle.Language }
     * 
     */
    public PrestashopProduct.Product.MetaTitle.Language createPrestashopProductMetaTitleLanguage() {
        return new PrestashopProduct.Product.MetaTitle.Language();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.MetaKeywords.Language }
     * 
     */
    public PrestashopProduct.Product.MetaKeywords.Language createPrestashopProductMetaKeywordsLanguage() {
        return new PrestashopProduct.Product.MetaKeywords.Language();
    }

    /**
     * Create an instance of {@link PrestashopProduct.Product.MetaDescription.Language }
     * 
     */
    public PrestashopProduct.Product.MetaDescription.Language createPrestashopProductMetaDescriptionLanguage() {
        return new PrestashopProduct.Product.MetaDescription.Language();
    }

}
